version: "3.8"

services:
  importer:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.example
    ports:
      - 3000:3000
    volumes:
      - storage:/usr/app/storage

  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6
    command: redis-server --appendonly yes --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.example
    volumes:
      - storage:/usr/app/storage

volumes:
  postgres:
  redis:
  storage:
