development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { ENV.fetch("REDIS_URL", "redis://localhost:6379/1") } %>
  channel_prefix: importer_development
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>

test:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { ENV.fetch("REDIS_URL", "redis://localhost:6379/1") } %>
  channel_prefix: importer_test
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { ENV.fetch("REDIS_URL", "redis://localhost:6379/1") } %>
  channel_prefix: importer_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
