development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { ENV.fetch("REDIS_URL", "redis://localhost:6379/1") } %>
  channel_prefix: csvspace_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { ENV.fetch("REDIS_URL", "redis://localhost:6379/1") } %>
  channel_prefix: csvspace_production
