default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', "postgres://postgres:postgres@localhost:#{ENV.fetch('CSV_DB_PORT', '5432')}/importer_development") %>

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', "postgres://postgres:postgres@localhost:#{ENV.fetch('CSV_DB_PORT', '5432')}/importer_test") %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
