:schedule:
  reap_expired_batches:
    class: BatchExpiredJob
    cron: '0 1 * * *'
  reap_steps_in_limbo:
    class: StepInLimboJob
    cron: '0 * * * *'
  reap_unused_manifests:
    class: UnusedManifestJob
    cron: '0 0 1 * *'
